name: edX Platform JS Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Javascript Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '12.21.0' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Required System Packages
      run: |
        sudo apt-get update && sudo apt-get install libxmlsec1-dev xvfb

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Required Python Dependencies
      run: |
        pip install setuptools wheel
        pip install -r requirements/edx/base.txt

    - name: Run JS Tests
      env:
        FIREFOX_BIN: /usr/bin/firefox
        TEST_SUITE: js-unit
        SCRIPT_TO_RUN: ./scripts/generic-ci-tests.sh
      run: xvfb-run --auto-servernum ./scripts/all-tests.sh
